### ISSUE TITLE
TickThreading incompatibility with industrialcraft-2_2.0.354-experimental

### ISSUE THREAD

**Issue by Daniel86268** [MinimallyCorrect/TickThreading#1069]
The whole powersystem of industrialcraft 2 is broken:
-Cables aren't connecting to each other or to machines
-machines based on the ic2 powersystem aren't functioning
-Nuclear Reactors aren't doing anything

Without TickThreading everything works fine.

Also had a Chunk reset, couldn't figure out what caused it.

I used the latest mcpc+ version. (mcpc-plus-1.6.4-R2.1-forge965-B254)
Tested with TickThreading-1.6.4.116

Log:
https://gist.github.com/Daniel86268/e35af1732a14f5566a40

<script src="https://gist.github.com/Daniel86268/e35af1732a14f5566a40.js"></script>

**Comment by LunNova** [comment]
Use http://gist.github.com/ and put the full log there.

> Also had a Chunk reset, couldn't figure out what caused it.

You are doing this on a test server, right?

**Comment by Daniel86268** [comment]
I've tested it on a backup of my normal server where I've built a bunch of things (which was therefore a good testing environment). So I can say this is a test server. 
Don't worry, none of my things or buildings broke really ;). (I've expected things to break or crash)

**Comment by Daniel86268** [comment]
I did further testing:
With concurrentmovementupdates set to false the industrialcraft Powersystem seems to work perfectly. 
Also Minecarts get stuck when mounted and can't be dismounted with concurrentmovementupdates enabled.

**Comment by ruifung** [comment]
Not just minecarts, boats too. And probably any entity you can ride in general.

**Comment by Daniel86268** [comment]
I figured the Chunk Reset out: Tickthreading is somehow incompatible with the MFR Grinder.
(MineFactoryReloaded-2.7.9-final)

**Comment by LunNova** [comment]
Can you confirm that the issues mentioned here are now fixed?

**Comment by Vycraftujto** [comment]
not fixed cables still not conecting

**Comment by Daniel86268** [comment]
With the latest TickThreading version (TickThreading-1.6.4.153.jar) the IC2 power system works like a charm: all cables are connecting, machines are working, etc. Great work :)
The chunkreset still happens with the MFR grinder.
The minecart riding works with concurrentmovementupdates enabled, and dismounting works now. But my client crashed suddenly while riding. Client crash report: 
https://gist.github.com/Daniel86268/d794d04dca12d78a140e
Seems like some sort of incompatibility with codechicken.multipart. This only occurs when I ride a minecart (didn't test other entities by now). When I walk the same path nothing crashes.

**Comment by Vycraftujto** [comment]
reali ? we just tested latest and cables dont connect

**Comment by Daniel86268** [comment]
That is strange. Which minecraft server and which Industrialcraft 2 version are you using?
I am using mcpc+ and industrialcraft-2_2.0.354-experimental.

**Comment by Vycraftujto** [comment]
industrialcraft-2_2.0.397-experimental.jar

it just start working .... wierd.....

**Comment by Daniel86268** [comment]
Maybe it was just a bit of startup lag, need for a block update, or something like that.

**Comment by LunNova** [comment]
The client crash is a known FMP issue: https://github.com/Chicken-Bones/ForgeMultipart/issues/139

Is TT making it happen more often?

About IC2 cables, guess they're not fixed. With threaded code you can have errors that are non-deterministic - a slight timing change can cause it to fail or work, so even just restarting the same server with no change made might fix it.

The grinder will be fixed soon.

**Comment by Daniel86268** [comment]
The client crash is a known FMP issue: Chicken-Bones/ForgeMultipart#139
Without TickThreading I haven't this crash a single time, with TickThreading nearly every time I ride a Minecart.
About IC2 cables: Thanks for the update, Looking forward to the future, when it's completely fixed :)
    The grinder will be fixed soon.
Awesome :D

**Comment by LunNova** [comment]
If you manage to get the IC2 issue to happen, please right click both a broken machine and broken cable with a clock while opped, and pastebin the output. You can also run /dump x y z (of the machine/cable) to get the same info in console.

**Comment by floh22** [comment]
Just saying but I had an MFR Grinder reset a chunk without TT installed. TT might make it more likely, but it can certainly happen without it

**Comment by Daniel86268** [comment]
I never had a chunk reset on my server with minecraft 1.6.4 before and as soon as i put a MFR grinder down while having TickThreading installed it crashes. 
Chunk reset propability without TickThreading ~0% with TickThreading ~100% if you want so ;).

**Comment by LunNova** [comment]
Issue for MFR grinder chunk reset: #1088
