### ISSUE TITLE
#1260 Chunk save/reload debugging 

### ISSUE THREAD

**Issue by HaoSs07** [MinimallyCorrect/TickThreading#284]
https://gist.github.com/HaoSs07/5372918
edit1
@nallar do you have a IRQ ?

edit2

04-12 18:53:02 [WARNING] [TickThreading] Save queue overloaded in Overworld/0 consider decreasing saveInterval. Only saved 128 out of 1321
04-12 18:53:02 [WARNING] [TickThreading] Save queue overloaded in Twilight Forest/7 consider decreasing saveInterval. Only saved 128 out of 159
04-12 18:53:03 [WARNING] [TickThreading] Reloaded chunk at -124554051576: 8,-29 before queued unload was processed.
java.lang.Throwable
  at im.getChunkAt(ThreadedChunkProvider.java:383)
  at im.d(ThreadedChunkProvider.java:295)
  at yc.e(World.java:524)
  at yc.a(World.java:111)
  at akz.b(SourceFile:46)
  at in.run(WorldServer.java:476)
  at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
  at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)

**Comment by Puremin0rez** [comment]
Getting lots of the same too

It always appears to be overloaded every save and i'm on default everything.

**Comment by HaoSs07** [comment]
iah , nallar added some debugging with 1260 is its probably a good idea to let the server run for a wile and add your TT log here, lets hope he can fix the broken chunk save from our data

**Comment by LunNova** [comment]
I changed the default world save interval recently to be smaller. It no longer saves all chunks containing entities at every save like vanilla does, so it's better to reduce the interval as the warning notes.

**Comment by HaoSs07** [comment]
yah but does not saving all chunks lead to duplication bugs or item lose ? i have tons of reports from players moving items from 1 chunk to another and losing a big part of them due to no save, (as you may expect 90 %  forget to report the duplication bugs )

also does TT changes mc save-all ? i have a command block that runs save-all every 10 minutes, also if my gamecp reboots the server id does a /save-all and a /stop but players report missing items after reboots, machine just placed disappearing, items on disks from applied energetics disappearing, etc

**Comment by LunNova** [comment]
And it's still been happening since updating? When a chunk is unloaded, it should still always be saved, this is just for the saving which happens while a chunk is loaded in case the server loses power.

**Comment by HaoSs07** [comment]
I switched to 1260 4 hours ago and last report of item lose was after 1 hours , iupdated again 10 minutes ago. still testing 
this is my console now:

04-12 22:41:17 [WARNING] [TickThreading] Reloaded chunk at -485331304532: -84,-114 before queued unload was processed.
java.lang.Throwable
at im.getChunkAt(ThreadedChunkProvider.java:383)
at im.d(ThreadedChunkProvider.java:295)
at yc.e(World.java:524)
at yc.d(World.java:516)
at factorization.common.TileEntityWrathLamp.findLightAirParent(TileEntityWrathLamp.java:92)
at factorization.common.TileEntityWrathLamp.doAirCheck(TileEntityWrathLamp.java:61)
at factorization.common.BlockLightAir.b(BlockLightAir.java:88)
at in.run(WorldServer.java:476)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
04-12 22:41:17 [WARNING] [TickThreading] Reloaded chunk at -635655159856: -48,-149 before queued unload was processed.
java.lang.Throwable
at im.getChunkAt(ThreadedChunkProvider.java:383)
at im.d(ThreadedChunkProvider.java:295)
at yc.e(World.java:524)
at yc.d(World.java:516)
at factorization.common.TileEntityWrathLamp.findLightAirParent(TileEntityWrathLamp.java:92)
at factorization.common.TileEntityWrathLamp.doAirCheck(TileEntityWrathLamp.java:61)
at factorization.common.BlockLightAir.b(BlockLightAir.java:88)
at in.run(WorldServer.java:476)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
04-12 22:41:17 [WARNING] [TickThreading] Reloaded chunk at -485331304530: -82,-114 before queued unload was processed.
java.lang.Throwable
at im.getChunkAt(ThreadedChunkProvider.java:383)
at im.d(ThreadedChunkProvider.java:295)
at yc.e(World.java:524)
at yc.d(World.java:516)
at factorization.common.TileEntityWrathLamp.findLightAirParent(TileEntityWrathLamp.java:92)
at factorization.common.TileEntityWrathLamp.doAirCheck(TileEntityWrathLamp.java:61)
at factorization.common.BlockLightAir.b(BlockLightAir.java:88)
at in.run(WorldServer.java:476)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
04-12 22:41:17 [WARNING] [TickThreading] Reloaded chunk at -644245094446: -46,-151 before queued unload was processed.
java.lang.Throwable
at im.getChunkAt(ThreadedChunkProvider.java:383)
at im.d(ThreadedChunkProvider.java:295)
at yc.e(World.java:524)
at yc.d(World.java:516)
at factorization.common.TileEntityWrathLamp.findLightAirParent(TileEntityWrathLamp.java:92)
at factorization.common.TileEntityWrathLamp.doAirCheck(TileEntityWrathLamp.java:61)
at factorization.common.BlockLightAir.b(BlockLightAir.java:88)
at in.run(WorldServer.java:476)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
04-12 22:41:17 [WARNING] [TickThreading] Reloaded chunk at -635655159854: -46,-149 before queued unload was processed.
java.lang.Throwable
at im.getChunkAt(ThreadedChunkProvider.java:383)
at im.d(ThreadedChunkProvider.java:295)
at yc.e(World.java:524)
at yc.d(World.java:516)
at factorization.common.TileEntityWrathLamp.findLightAirParent(TileEntityWrathLamp.java:92)
at factorization.common.TileEntityWrathLamp.doAirCheck(TileEntityWrathLamp.java:61)
at factorization.common.BlockLightAir.b(BlockLightAir.java:88)
at in.run(WorldServer.java:476)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
04-12 22:41:17 [WARNING] [TickThreading] Reloaded chunk at -627065225274: -58,-147 before queued unload was processed.
java.lang.Throwable
at im.getChunkAt(ThreadedChunkProvider.java:383)
at im.d(ThreadedChunkProvider.java:295)
at yc.e(World.java:524)
at yc.d(World.java:516)
at factorization.common.TileEntityWrathLamp.findLightAirParent(TileEntityWrathLamp.java:92)
at factorization.common.TileEntityWrathLamp.doAirCheck(TileEntityWrathLamp.java:61)
at factorization.common.BlockLightAir.b(BlockLightAir.java:88)
at in.run(WorldServer.java:476)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
04-12 22:41:17 [WARNING] [TickThreading] Reloaded chunk at -627065225275: -59,-147 before queued unload was processed.
java.lang.Throwable
at im.getChunkAt(ThreadedChunkProvider.java:383)
at im.d(ThreadedChunkProvider.java:295)
at yc.e(World.java:524)
at yc.d(World.java:516)
at factorization.common.TileEntityWrathLamp.findLightAirParent(TileEntityWrathLamp.java:92)
at factorization.common.TileEntityWrathLamp.doAirCheck(TileEntityWrathLamp.java:61)
at factorization.common.BlockLightAir.b(BlockLightAir.java:88)
at in.run(WorldServer.java:476)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
04-12 22:41:17 [WARNING] [TickThreading] Reloaded chunk at -618475290683: -59,-145 before queued unload was processed.
java.lang.Throwable
at im.getChunkAt(ThreadedChunkProvider.java:383)
at im.d(ThreadedChunkProvider.java:295)
at yc.e(World.java:524)
at yc.d(World.java:516)
at factorization.common.TileEntityWrathLamp.findLightAirParent(TileEntityWrathLamp.java:92)
at factorization.common.TileEntityWrathLamp.doAirCheck(TileEntityWrathLamp.java:61)
at factorization.common.BlockLightAir.b(BlockLightAir.java:88)
at in.run(WorldServer.java:476)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
04-12 22:41:17 [WARNING] [TickThreading] Reloaded chunk at -141733920772: -4,-34 before queued unload was processed.
java.lang.Throwable
at im.getChunkAt(ThreadedChunkProvider.java:383)
at im.d(ThreadedChunkProvider.java:295)
at yc.e(World.java:524)
at yc.a(World.java:111)
at yc.c(World.java:433)
at akz.b(SourceFile:63)
at in.run(WorldServer.java:476)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
04-12 22:41:17 [WARNING] [TickThreading] Reloaded chunk at -622770257977: -57,-146 before queued unload was processed.
java.lang.Throwable
at im.getChunkAt(ThreadedChunkProvider.java:383)
at im.d(ThreadedChunkProvider.java:295)
at yc.e(World.java:524)
at yc.d(World.java:516)
at factorization.common.TileEntityWrathLamp.findLightAirParent(TileEntityWrathLamp.java:92)
at factorization.common.TileEntityWrathLamp.doAirCheck(TileEntityWrathLamp.java:61)
at factorization.common.BlockLightAir.b(BlockLightAir.java:88)
at in.run(WorldServer.java:476)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
04-12 22:41:17 [WARNING] [TickThreading] Reloaded chunk at -627065225273: -57,-147 before queued unload was processed.
java.lang.Throwable
at im.getChunkAt(ThreadedChunkProvider.java:383)
at im.d(ThreadedChunkProvider.java:295)
at yc.e(World.java:524)
at yc.d(World.java:516)
at factorization.common.TileEntityWrathLamp.findLightAirParent(TileEntityWrathLamp.java:92)
at factorization.common.TileEntityWrathLamp.doAirCheck(TileEntityWrathLamp.java:61)
at factorization.common.BlockLightAir.b(BlockLightAir.java:88)
at in.run(WorldServer.java:476)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
04-12 22:41:17 [WARNING] [TickThreading] Reloaded chunk at -618475290681: -57,-145 before queued unload was processed.
java.lang.Throwable
at im.getChunkAt(ThreadedChunkProvider.java:383)
at im.d(ThreadedChunkProvider.java:295)
at yc.e(World.java:524)
at yc.d(World.java:516)
at factorization.common.TileEntityWrathLamp.findLightAirParent(TileEntityWrathLamp.java:92)
at factorization.common.TileEntityWrathLamp.doAirCheck(TileEntityWrathLamp.java:61)
at factorization.common.BlockLightAir.b(BlockLightAir.java:88)
at in.run(WorldServer.java:476)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
04-12 22:41:34 [INFO] [Minecraft] remenyic blew up

not allways from factorization, sometimes is buildcraft or dan200 (turtles)

**Comment by HaoSs07** [comment]
will continue to test, also the : Reloaded chunk before queued unload was processed is normal ?

**Comment by LunNova** [comment]
It's not a good thing - it indicates that a mod/minecraft is doing something wrong and causing chunks to load when it shouldn't - but it shouldn't break anything. Although previously it seems that it has caused chunks not to be saved, which is why it gets logged.

**Comment by HaoSs07** [comment]
well i get tons of warnings about that https://gist.github.com/HaoSs07/5375102
and is not 1 mod, factorization does it, ic2,buildcraft,redpower,turtles,thermal expansion, xycraft, oh man; i miss the good old days when the only problem i had was people swearing on my server

**Comment by LunNova** [comment]
Fixed some of those. Turn off loadChunkOnProvideRequest and it should go away completely, but that might break some other stuff.

**Comment by HaoSs07** [comment]
important stuff?

also side note: player have reported timers stopping with energy on, ( this is pre build 1260 ) sometime the player is next to the timer and it stops..

**Comment by LunNova** [comment]
That might be the issue just fixed in 8f468e1a7c32a70. Is the timer on a chunk boundary?

**Comment by LunNova** [comment]
loadChunkOnProvideRequest = false may break IC2 reactors on chunk boundaries and chickenchunks chunkloaders.

**Comment by HaoSs07** [comment]
1 timer was in the middle of the chunk, and another one was at the edge , both on the same chunk, will test if it works now

**Comment by HaoSs07** [comment]
It seems the problem persists ,the 2 timers on the same chunk have stopped at the same time

**Comment by LunNova** [comment]
Do other timers continue to work? Is this chunk loaded with a chunkloader?

**Comment by HaoSs07** [comment]
mine work fine,i'm on other zone and i use chickenchunk loader

the player that reported uses a world anchor , i gived him more timers to put in different chunks , will come back with reply

i had a similar case in nether this morning, but the player in question is not on,

**Comment by HaoSs07** [comment]
he used more timers on other chunks, they stopped at the same time, if a cable that connected to the timer got broken the timer start rotating again,
also i told him to remove the anchor, did not help

he used 4 timers, in 3 different side by side chunks, first time all 4 stoped, second time (after world anchor removal )3 timers have stopped; 1 is still working , so strange

**Comment by LunNova** [comment]
Debug spam disabled, as this seems fixed. Make a new issue about the timers.

**Comment by HaoSs07** [comment]
thx nallar, Don't know if you did something but with the last build timers seem to work...
